version: 0.2
env:
  variables:
    APP_NAME: "votea"
phases:
  install:
    commands:
      - echo install process started
      - cd huutoapp
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://voteaapp.s3-website.eu-north-1.amazonaws.com --delete
